### ISSUE TITLE
Swarmpit registry crash ?

### ISSUE THREAD

**Issue by sNohz** [swarmlet/swarmlet#16]
Hey, I've setup Swarmlet 3 days ago but since yesterday I'm getting an error when deploying with git or stopping a service through Swarmpit.

On Swarmpit I get : 'Service stopping failed. No matching registry ( 127.0.0.1:5000 ) linked with Swarmpit'

On git push : 'remote: Get http://127.0.0.1:5000/v2/: dial tcp 127.0.0.1:5000: connect: connection refused'

I tried restarting the server/containers but it didn't solved anything.

Did I make something wrong ? Is there a fix ?

Thanks,

**Comment by woudsma** [comment]
That's weird.
I've not experienced this myself, and I've been running a Swarmlet on a cluster for over a month.
Have you tried this?
```sh
cd /opt/swarmlet/services/registry
docker-compose up -d
```
And what is the output of `docker container ls`?
Do you this line in the output?
```
911f5779e454    registry:2    "/entrypoint.sh /etc…"    5 weeks ago  Up 4 days    0.0.0.0:5000->5000/tcp    registry_registry_1
```

**Comment by sNohz** [comment]
Registry was missing from 'container ls' just now (wasn't yesterday).
I started it, deploy through git is now fixed but not control from Swarmpit.

After a server reboot, no more registry in 'container ls', maybe the autostart is missing ?

**Comment by woudsma** [comment]
I've added the `restart: always` policy to the registry's `docker-compose.yml` in https://github.com/swarmlet/swarmlet/commit/47fcfad090d44fd7f52b40dcc2f6ef0173c43521
Closing this for now, please re-open if this does not fix your issue.

**Comment by sNohz** [comment]
This permanently fixed the issue for git push but nothing changed for swarmpit actions, still getting "Service redeploy failed. No matching registry ( 127.0.0.1:5000 ) linked with Swarmpit"

**Comment by woudsma** [comment]
My bad, I misread your comment about Swarmpit.

I'm getting the same error when trying to redeploy a service using Swarmpit.
Swarmpit cannot access 127.0.0.1:5000 so it seems.
I've just tried linking a registry (v2) in the Swarmpit UI, but after adding swarmlet-network to both swarmpit_app and swarmpit_agent it still does not work.
Please let me know if you find some clues while I'll investigate as well.

**Comment by woudsma** [comment]
I'm diving into this the few coming days. https://github.com/swarmlet/swarmlet/issues/25

**Comment by woudsma** [comment]
I've updated the develop branch, you can now link the Swarmlet registry in Swarmpit, providing:
```
Registry account type: Registry v2
Name: swarmlet-registry
Url: http://swarmlet-registry:5000
Secured access: True
Username: <username configured during installation>
Password: <password configured during installation>
```
